### ISSUE TITLE
Quero me tornar um Devolunteer

### ISSUE THREAD

**Issue by DemetriusLeonardoBantim** [devolunteers/quero-ser-um#4]
#### Apresentação

Meu nome é Demetrius Leonardo, tenho 23 anos, sou de Juazeiro do Norte CE e quero atuar como desenvolvedor fullstack.
Já tenho experiência com TS e quero muito aprender Ruby.

#### Habilidades

Já trabalhei com: 

- React 
- Vue
- Angular
- Node.JS
- TS
- JS
- postgresql

**Comment by aleDsz** [comment]
Convite enviado!

Entre em nosso servidor do discord: https://discord.gg/Hsu6bVC9Wg
